# Generated by Django 5.0.4 on 2024-04-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('phone', models.CharField(blank='True', max_length=35, null='True', verbose_name='телефон')),
                ('comment', models.CharField(blank='True', max_length=100, null='True', verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='тема письма')),
                ('text', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ('theme',),
            },
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank='True', null='True', verbose_name='дата и время первой отправки')),
                ('period', models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='раз в месяц', max_length=5, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('created', 'создана'), ('executed', 'запущена'), ('finished', 'завершена')], default='создана', max_length=15, verbose_name='статус')),
                ('clients', models.ManyToManyField(to='main.client', verbose_name='клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('sent_at',),
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_tried_at', models.DateTimeField(auto_now_add=True, verbose_name='последняя попытка')),
                ('status', models.BooleanField(default=False, verbose_name='статус')),
                ('server_response', models.CharField(verbose_name='ответ почтового сервера')),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sending', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ('last_tried_at',),
            },
        ),
    ]
