# Generated by Django 5.0.4 on 2024-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sending_clients_alter_sending_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='period',
            field=models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], default='раз в месяц', max_length=12, verbose_name='периодичность'),
        ),
    ]
