# Generated by Django 5.0.4 on 2024-04-22 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sending_finish_at_alter_sending_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'ordering': ('sent_at',), 'permissions': [('set_active', 'Can deactivate sending')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='sending',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 22, 40, 33, 275645), verbose_name='дата окончания'),
        ),
    ]
