# Generated by Django 5.0.4 on 2024-04-22 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_sending_finish_at_alter_sending_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 21, 6, 20, 637449, tzinfo=datetime.timezone.utc), verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 21, 6, 20, 637449, tzinfo=datetime.timezone.utc), verbose_name='дата начала'),
        ),
    ]
