# Generated by Django 5.0.4 on 2024-04-23 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_sending_finish_at_alter_sending_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='finish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 7, 55, 21, 301058, tzinfo=datetime.timezone.utc), verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 7, 55, 21, 301058, tzinfo=datetime.timezone.utc), verbose_name='дата начала'),
        ),
    ]
